language: java
jdk:
- oraclejdk8
notifications:
  slack:
    rooms:
      secure: Tupshz+pR+Uy2Pffig+H6e0RijcmK3ovFZPDvKSjJXnKMXSYYqwD6qNhDIxB1XI63hRrzmf+JW/bZlSAwEb/fukxWG7ZFopOW/2lr37G64oldhSCrowv7kmOEocweU9Wn6eDsr58OM+X0T34sBeZRvd8GJTq5Zn13olunGsGGtOLwgJ3PF75IPB+Ut/Pdqtye6EqBtz3LIoHuCK24logMdqruigQfQbdoAJunMencCPnHF6klUe0ZDD0/4fggzRwhv9dk/BAygnrgbZc4ISwOu1T0Cp5lbCHFmE3YM45jH47ihcDDUgSOyiAjPsvFhpfg0IAIn5L1ciAbnneqSip7/miD5QaD3CjnhjBYf3va5hvTAPJmDZT21Uj5At7jwh8dDKDjZWDoPXZwdlWnoXCZ61bnS0LvXB+bfa0DeYv0+/BYVm7Y41XhEMrODGkObVBALVm+/lBTmQWrsD+/jFaepZuCp71/Iz4ZK5gcwER++pUtmRSoq2Cx6VT2JDlvGjutSylQincLk8R/GJfhIAnX6xmxLM13BqeIqdPP9vk5Eua6wJd2rrxqTZ2T3aHfaD48HDX5lP8n8XcHXdGRvrC9vmFSpkQq86ViDvyBBLgSlU4PE22VvIQd2zCu6/Kke/CAQ0SEOrKLfkJVvnwd1I3bSGSznWXIfu0z4mJKKa7RNM=
