language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: UezLsdSxYZZrtrjdyQgzh5famasSD3bszKCPbWvJFZO7rTdsIAnwZ00sXtwGMGhygV7uWxPjpXhwqQInRmkzGy0NayZF4HisvBYAFXzHd+MTY3mxJEZWG3o2GOZM7gZTH4Q3CcfWZY1npz1c081xzvB0z/XEuZ59zaYNR1B42vFKfW02+DwR/Irtllr7S0YywMVy3hCp384rf+e89mfqxPB2voyRDcCcubVJbmjMT0K4Yj6R+Pt/+OzWATHYYTf1GfEX4tj0YFOvpafs+0oQRFwSbSRheuXYpY/guAOs2T/3UlnZK5FJQLRBU5Mru3C04ZIL7CSgz1091HQ/Gp23RfZt9wP/Xlt9U3Ij5XgRV3NkOQPT6RLc3ohm2Pp7OH0jzIGHt+3bQVi0uGQnp+rF1Q6T3kwvnTK0A3IQNxMEPQGSsJ2md69uZ2/nygJeHwIWNT4oKzOnXI1GbqXooi1SYhVMsm3JDIRZIK06VGFGxsL5GeYlDCv8PFBv2NnJH90wrHaOSbtYKTT77vuS1ZaCGltlOud2NYt9kdmhjwDrtZssn15M2xIkAW7E0stIhk1kYSqV7GM+G5Jp8K1qGbe6yOMuEGgjMVwXUJENYrcUeOaeltKpaz/9k2e6Bk3OruRTF6TUUlAi+6ECYis9pbuCRNQVMY4j5gk1YyvbOTfR2Es=
