package com.github.inventorytracker.verticle.http.routing;

import io.vertx.core.Vertx;
import io.vertx.core.http.HttpServerResponse;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.RoutingContext;

public class FrontendHandler {

    public Router router(Vertx vertx) {
        final Router sub = Router.router(vertx);
        sub.get("v1/budget/general/dashboard").handler(this::serveDashboard);
        return sub;
    }

    private void serveDashboard(RoutingContext ctx) {
        HttpServerResponse res = ctx.response();
        String response = "{\n"
                + "    balance: {\n"
                + "        plannedBalance: 0,\n"
                + "        actualBalance: 0,\n"
                + "        difference: 0\n"
                + "    },\n"
                + "    actualIncome: {\n"
                + "        incomes: [\n"
                + "            {\n"
                + "                name: '1. income',\n"
                + "                value: xxx,\n"
                + "                currency: 'Ft'\n"
                + "            },\n"
                + "            {\n"
                + "                name: '2. income',\n"
                + "                value: 0,\n"
                + "                currency: 'Ft'\n"
                + "            },\n"
                + "            {\n"
                + "                name: 'Extra income',\n"
                + "                value: 0,\n"
                + "                currency: 'Ft'\n"
                + "            }\n"
                + "        ],\n"
                + "        summary: {\n"
                + "            value: 0,\n"
                + "            currency: 'Ft'\n"
                + "        }\n"
                + "    },\n"
                + "    plannedIncome: {\n"
                + "        incomes: [\n"
                + "            {\n"
                + "                name: '1. income',\n"
                + "                value: xxx,\n"
                + "                currency: 'Ft'\n"
                + "            },\n"
                + "            {\n"
                + "                name: '2. income',\n"
                + "                value: 0,\n"
                + "                currency: 'Ft'\n"
                + "            },\n"
                + "            {\n"
                + "                name: 'Extra income',\n"
                + "                value: 0,\n"
                + "                currency: 'Ft'\n"
                + "            }\n"
                + "        ],\n"
                + "        summary: {\n"
                + "            value: 0,\n"
                + "            currency: 'Ft'\n"
                + "        }\n"
                + "    },\n"
                + "    actualExpense: {\n"
                + "        value: 0,\n"
                + "        currency: 'Ft'\n"
                + "    },\n"
                + "    plannedExpense: {\n"
                + "        value: 0,\n"
                + "        currency: 'Ft'\n"
                + "    },\n"
                + "    cathegories: [\n"
                + "        {\n"
                + "            id: 0,\n"
                + "            name: 'Food',\n"
                + "            subcathegories: [\n"
                + "                {\n"
                + "                    id: 10,\n"
                + "                    name: 'Bread'\n"
                + "                }, {\n"
                + "                    id: 11,\n"
                + "                    name: 'Popcorn'\n"
                + "                }\n"
                + "            ]\n"
                + "        }, {\n"
                + "            id: 1,\n"
                + "            name: 'Entertainment',\n"
                + "            subcathegories: [{\n"
                + "                    id: 10,\n"
                + "                    name: 'Cinema'\n"
                + "                }, {\n"
                + "                    id: 11,\n"
                + "                    name: 'Theater'\n"
                + "                }\n"
                + "            ]\n"
                + "        }\n"
                + "    ],\n"
                + "    expenseTable: {\n"
                + "        rows: [\n"
                + "            {\n"
                + "                name: 'Food',\n"
                + "                plannedExpense: 0,\n"
                + "                actualExpense: 0,\n"
                + "                difference: 0,\n"
                + "                currency: ''\n"
                + "            }, {\n"
                + "                name: 'Entertainment',\n"
                + "                plannedExpense: 0,\n"
                + "                actualExpense: 0,\n"
                + "                difference: 0,\n"
                + "                currency: ''\n"
                + "        },\n"
                + "        ],\n"
                + "        summary: {\n"
                + "            plannedExpense: 0,\n"
                + "            actualExpense: 0,\n"
                + "            difference: 0,\n"
                + "            currency: 'Ft'\n"
                + "        }\n"
                + "    }";
        res.end(response);
    }
}
